schema: https://raw.githubusercontent.com/strimzi/strimzi-admin/d73f77de68ad15d5b155d7e555200393b5b68596/kafka-admin/src/main/resources/graphql-schema/kafka-admin.graphql

extensions:
  codegen:
    generates:
      ./client/Entities/Entities.generated.ts:
        plugins:
          - typescript
          - typescript-react-apollo
    config:
      skipTypeNameForRoot: true
      skipTypename: true
